--| Monarch Core SQL Schema |--
--| Installation and Update |--

CREATE TABLE IF NOT EXISTS `users` (
  `userId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `license` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `license2` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fivem` VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `steam` VARCHAR(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `discord` VARCHAR(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `users`
  DROP PRIMARY KEY;

ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `userId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
  ADD PRIMARY KEY (`userId`);

ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `username` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `license` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `license2` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `fivem` VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `steam` VARCHAR(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `discord` VARCHAR(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL;

ALTER TABLE `users`
  MODIFY COLUMN `userId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY COLUMN `username` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  MODIFY COLUMN `license` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  MODIFY COLUMN `license2` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  MODIFY COLUMN `fivem` VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  MODIFY COLUMN `steam` VARCHAR(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  MODIFY COLUMN `discord` VARCHAR(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL;

ALTER TABLE `users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;